steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean','install', '-Dmaven.test.skip=true']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/idaithalam-server:1.0.$BUILD_ID', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/idaithalam-server:1.0.$BUILD_ID']
