openapi: 3.0.2
info:
  title: idaithalamserver
  version: 1.1.7
  description: Idaithalam Server
  contact:
    name: Oliver Glas
    url: 'http://inss.ch'
    email: oliver.glas@inss.ch
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  - url: 'http://api.idaithalam.io'
    description: Prod server
  - url: 'http://localhost:8080'
    description: Localhost
paths:
  /test:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - filestream
                - serverurl
              type: object
              properties:
                filestream:
                  format: binary
                  type: string
                serverurl:
                  format: url
                  description: The server url to be tested.
                  default: 'http://localhost:8080'
                  type: string
                  example: 'http://localhost:8080'
                execute:
                  format: stringboolean
                  description: 'Execute test immediately. If false, only the property file will be updated (append).'
                  default: true
                  type: string
                  example: true
                skipResponseValidation:
                  format: stringboolean
                  description: Skip the respone validation in tests.
                  default: true
                  type: string
                  example: true
      tags:
        - API test execution
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
          description: Test created.
        '400':
          description: Bad request.
        '418':
          description: I am a teapot.
        default:
          description: unexpected error
      operationId: testRun
      summary: Create and run the test with the uploaded Postman collection.
      description: Create a new test and run against an API. Generates the Cucumber report and a Gherkin file.
    get:
      tags:
        - Results
      
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Testidlist'
          description: List of all test IDs.
        '404':
          description: No test found.
        '500':
          description: Internal server error.
        default:
          description: unexpected error
      operationId: listTest
      summary: Get all test IDs as a list.
      
      description: Get all test IDs as a list.
  '/test/{testId}':
    get:
      tags:
        - Results
      parameters:
        - name: testId
          description: testId for that test
          schema:
            format: string
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
          description: Configuration of cucumblan.properties file.
        '404':
          description: Test not found.
        '500':
          description: Internal server error.
        default:
          description: unexpected error
      operationId: getReport
      summary: Get the test result links.
      description: Get the test result links.
    put:
      tags:
        - API test execution
      parameters:
        - name: testId
          description: testid for that test
          schema:
            format: uuid
            type: string
          in: path
          required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
          description: Gives back the entire cucumblan.properties file and generated testid.
      operationId: runTest
      summary: Run test.
      description: Run test
  '/test/{testId}/report':
    get:
      tags:
        - Results
      parameters:
        - name: testId
          description: testid for that test
          schema:
            format: string
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
          description: Configuration of cucumblan.properties file.
        '500':
          description: Internal server error.
        default:
          description: unexpected error
      operationId: report
      summary: Get the report for this uuid.
      description: Get the report of a previously executed test.
  '/test/{testId}/feature':
    get:
      tags:
        - Results
      parameters:
        - name: testId
          description: testid for that Gherkin file.
          schema:
            format: string
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            text/plain:
              schema:
                format: Gherkin
                type: string
          description: Content of the generated Gherkin feature file.
        '500':
          description: Internal server error.
        default:
          description: unexpected error
      operationId: getgherkin
      summary: Get the content of the generated Gherkin feature file.
      description: Get the content of the generated Gherkin feature file.
  /health:
    get:
      tags:
        - health
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
              example:
                status: UP
          description: OK
        '503':
          description: Server not available.
      operationId: health
      summary: The health check of this service.
      description: The health check of this service.
  '/test/{testId}/conf':
    get:
      tags:
        - Configuration
      parameters:
        - name: testId
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            text/plain:
              schema:
                format: properties
                type: string
          description: Configuration of cucumblan.properties file.
        '404':
          description: Test not found.
        '500':
          description: Internal server error.
        default:
          description: unexpected error
      operationId: getConfProperty
      summary: Get the test configuration content from the cucumblan.properties.
      description: Get the content of the configured cucumblan.properties.
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Conf'
        required: true
      tags:
        - Configuration
      parameters:
        - name: testId
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            text/plain:
              schema:
                format: properties
                type: string
          description: Gives back the entire test configuration as a cucumblan.properties file.
        '400':
          description: Bad request.
        default:
          description: unexpected error
      operationId: updateConf
      summary: Update the configuration.
      description: Update the configuration.
    delete:
      tags:
        - Configuration
      parameters:
        - name: configKey
          description: remove given key configuration.
          schema:
            type: string
          example: 'service.api.pets'
          in: query
          required: true
        - name: testId
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            text/plain:
              schema:
                format: properties
                type: string
          description: delete key Configuration of cucumblan.properties file.
      operationId: removeConf
      summary: Remove the single config configuration.
      description: Remove the test.
    parameters:
      - name: testId
        schema:
          type: string
        in: path
        required: true
components:
  schemas:
   
    HealthResponse:
      required:
        - status
      type: object
      properties:
        status:
          enum:
            - UP
            - ERROR
          type: string
    Report:
      description: ''
      type: object
      properties:
        testId:
          description: ''
          type: string
          format: uuid
        success:
          description: ''
          type: boolean
        sessionNr:
          format: int32
          description: ''
          type: integer
        testExecuted:
          description: ''
          type: boolean
        skipResponseValidation:
          description: ''
          type: boolean
        creationTime:
          format: datetime
          description: ''
          type: string
        startTime:
          format: datetime
          description: ''
          type: string
        endTime:
          format: datetime
          description: ''
          type: string
        durationSeconds:
          format: time
          description: ''
          type: string
        linkToFeature:
          description: ''
          type: string
        linkToReport:
          description: ''
          type: string
        linkToProperties:
          description: ''
          type: string
        linkToSessions:
          description: ''
          type: string
        message:
          description: ''
          type: string
        error:
          description: ''
          type: string
    Conf:
      description: ''
      type: object
      properties:
        serverUrl:
          description: ''
          type: array
          items:
            type: string
    Testidlist:
      description: 'List of all test IDs.'
      type: object
      properties:
        serverUrl:
          description: 'Array of all testlinks.'
          type: array
          items:
            type: string
        idList:
          description: 'Array of all test IDs.'
          type: array
          items:
            type: string
tags:
  - name: API test execution
    description: Run a test against an API and generate the Cucumber report and a Gherkin file.
  - name: Results
    description: Test results and reports of the test sessions
  - name: Configuration
    description: Configuration of the test sessions in the cucumblan.properties file.
  - name: health
    description: Health of the server.